#include "LowpowerTest.h"
GPIO_InitTypeDef GPIO_InitStruct = {0};

void gpioLowpowerTest(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, uint32_t GpioMode,uint32_t PullMode)
{
    GPIO_InitStruct.Pin =GPIO_Pin;
    GPIO_InitStruct.Mode = GpioMode;
    GPIO_InitStruct.Pull = PullMode;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOx, &GPIO_InitStruct);

}

void gpioLowpowerIOSET(GPIO_TypeDef* GPIOx)
{
		gpioLowpowerTest(GPIOx, GPIO_PIN_0, GPIO_MODE_INPUT,GPIO_PULLDOWN);
		gpioLowpowerTest(GPIOx, GPIO_PIN_0, GPIO_MODE_INPUT,GPIO_PULLUP);
	
		gpioLowpowerTest(GPIOx, GPIO_PIN_1, GPIO_MODE_INPUT,GPIO_PULLDOWN);
	gpioLowpowerTest(GPIOx, GPIO_PIN_1, GPIO_MODE_INPUT,GPIO_PULLUP);
	
			gpioLowpowerTest(GPIOx, GPIO_PIN_2, GPIO_MODE_INPUT,GPIO_PULLDOWN);
		gpioLowpowerTest(GPIOx, GPIO_PIN_2, GPIO_MODE_INPUT,GPIO_PULLUP);
	
		gpioLowpowerTest(GPIOx, GPIO_PIN_3, GPIO_MODE_INPUT,GPIO_PULLDOWN);
		gpioLowpowerTest(GPIOx, GPIO_PIN_3, GPIO_MODE_INPUT,GPIO_PULLUP);
	
		gpioLowpowerTest(GPIOx, GPIO_PIN_4, GPIO_MODE_INPUT,GPIO_PULLDOWN);
		gpioLowpowerTest(GPIOx, GPIO_PIN_4, GPIO_MODE_INPUT,GPIO_PULLUP);
	
		gpioLowpowerTest(GPIOx, GPIO_PIN_5, GPIO_MODE_INPUT,GPIO_PULLDOWN);
		gpioLowpowerTest(GPIOx, GPIO_PIN_5, GPIO_MODE_INPUT,GPIO_PULLUP);
	
		gpioLowpowerTest(GPIOx, GPIO_PIN_6, GPIO_MODE_INPUT,GPIO_PULLDOWN);
		gpioLowpowerTest(GPIOx, GPIO_PIN_6, GPIO_MODE_INPUT,GPIO_PULLUP);
	
		gpioLowpowerTest(GPIOx, GPIO_PIN_7, GPIO_MODE_INPUT,GPIO_PULLDOWN);
		gpioLowpowerTest(GPIOx, GPIO_PIN_7, GPIO_MODE_INPUT,GPIO_PULLUP);
	
		gpioLowpowerTest(GPIOx, GPIO_PIN_8, GPIO_MODE_INPUT,GPIO_PULLDOWN);
		gpioLowpowerTest(GPIOx, GPIO_PIN_8, GPIO_MODE_INPUT,GPIO_PULLUP);
	
		gpioLowpowerTest(GPIOx, GPIO_PIN_9, GPIO_MODE_INPUT,GPIO_PULLDOWN);
		gpioLowpowerTest(GPIOx, GPIO_PIN_9, GPIO_MODE_INPUT,GPIO_PULLUP);
	
		gpioLowpowerTest(GPIOx, GPIO_PIN_10, GPIO_MODE_INPUT,GPIO_PULLDOWN);
		gpioLowpowerTest(GPIOx, GPIO_PIN_10, GPIO_MODE_INPUT,GPIO_PULLUP);
	
		gpioLowpowerTest(GPIOx, GPIO_PIN_11, GPIO_MODE_INPUT,GPIO_PULLDOWN);
		gpioLowpowerTest(GPIOx, GPIO_PIN_11, GPIO_MODE_INPUT,GPIO_PULLUP);
	
		gpioLowpowerTest(GPIOx, GPIO_PIN_12, GPIO_MODE_INPUT,GPIO_PULLDOWN);
		gpioLowpowerTest(GPIOx, GPIO_PIN_12, GPIO_MODE_INPUT,GPIO_PULLUP);
	
		gpioLowpowerTest(GPIOx, GPIO_PIN_13, GPIO_MODE_INPUT,GPIO_PULLDOWN);
		gpioLowpowerTest(GPIOx, GPIO_PIN_13, GPIO_MODE_INPUT,GPIO_PULLUP);
	
		gpioLowpowerTest(GPIOx, GPIO_PIN_14, GPIO_MODE_INPUT,GPIO_PULLDOWN);
		gpioLowpowerTest(GPIOx, GPIO_PIN_14, GPIO_MODE_INPUT,GPIO_PULLUP);
	
		gpioLowpowerTest(GPIOx, GPIO_PIN_15, GPIO_MODE_INPUT,GPIO_PULLDOWN);
		gpioLowpowerTest(GPIOx, GPIO_PIN_15, GPIO_MODE_INPUT,GPIO_PULLUP);

}
